### ISSUE TITLE
The "Versions" overview of roles are not updated.

### ISSUE THREAD

**Issue by robertdebock** [ansible/galaxy#924] opened 2018-07-19 05:25 UTC
##### SUMMARY
After creating [a release](https://github.com/robertdebock/ansible-role-bootstrap/releases/tag/2018.07.19) the version is not found [on galaxy](https://galaxy.ansible.com/robertdebock/bootstrap).
##### STEPS TO REPRODUCE
1. In GitHub, create a release.
2. Let it build successfully.
3. Find that no new version is visible on Galaxy.

##### EXPECTED RESULTS
I would expect a version to be available on Galaxy.

##### ACTUAL RESULTS
Only older versions are visible.

**Comment by tecris** [comment] 2018-07-19 06:01
Have the same problem for [role](https://galaxy.ansible.com/tecris/maven).
While I cannot point to an exact date, it seems it's related to the new Galaxy UI. Since this change the version list visible in the role page does not list the entire [github version list](https://github.com/tecris/ansible-maven/releases) .

**Comment by chouseknecht** [comment] 2018-07-19 06:57
In order for a git tag to be imported as a version, the tag name needs to match the [Semantic Versioni](https://semver.org) spec.

**Comment by tecris** [comment] 2018-07-19 07:10
[Ouch](https://semver.org/#spec-item-2)

Thanks, that explains for [role](https://galaxy.ansible.com/tecris/maven)
Seems I have to move away from time based version.

**Comment by chouseknecht** [comment] 2018-07-19 13:54
Duplicate of #914. Closing.

**Closed by chouseknecht** 2018-07-19 13:54 UTC
Labels: type/question
