### ISSUE TITLE
Error importing content from GitHub

### ISSUE THREAD

**Issue by grahamlyons** [ansible/galaxy#350] opened 2018-03-01 15:49 UTC
When:
 - I log into Ansible Galaxy
 - navgiate to https://galaxy.ansible.com/roleadd#/
 - click "Refresh Your Repositories from GitHub"

Then:
 - the spinner spins
 - the response in the network tab in my browser shows a 500
 - the content of the 500 contains, "An error occurred while loading the requested page. Please report this error by opening an issue at Galaxy Issues."

**Comment by robertdebock** [comment] 2018-03-01 16:26
Related to #348 (which relates to #349).

**Comment by chouseknecht** [comment] 2018-03-02 15:01
@grahamlyons 

Thanks for reporting the issue. There seems to have been some connectivity issues with the GitHub API yesterday.  Imports seem to be working OK today. We'll keep a closer eye on it, as the day progresses. 

Closing, as this is a duplicate of #348

**Closed** 2018-03-02 15:05 UTC
