### ISSUE TITLE
The API server (galaxy.ansible.com) is not responding, please try again later

### ISSUE THREAD

**Issue by marcossegovia** [ansible/galaxy#852] opened 2018-07-09 16:10 UTC
##### SUMMARY
In the last few weeks we have experimented that we cannot keep downloading roles inside our vagrant machine.

##### STEPS TO REPRODUCE
`ansible-galaxy install geerlingguy.ntp,1.3.0` 
gives 
`- the API server (galaxy.ansible.com) is not responding, please try again later.`
Inside our Vagrant box running Centos 6.7, with Ansible version ansible 1.9.4 and Python 2.6.6

##### EXPECTED RESULTS
```
ansible-galaxy install geerlingguy.ntp,1.3.0
- downloading role 'ntp', owned by geerlingguy
- downloading role from https://github.com/geerlingguy/ansible-role-ntp/archive/1.3.0.tar.gz
- extracting geerlingguy.ntp to /etc/ansible/roles/geerlingguy.ntp
```
Things we've tried so far:

- :white_check_mark: We've updated Vagrant to latest version
- :white_check_mark: I've rollback to previous Vagrantfile and provision versions, where roles where installed as expected.
- :white_check_mark: I've see whether has to do with certificates like in `/usr/lib/python2.6/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.` so I've also installed `pip install pyopenssl ndg-httpsclient pyasn` (https://github.com/nephila/djangocms-installer/issues/174)
- :white_check_mark: I've also tried to modify ansible galaxy bin like in : https://github.com/ansible/galaxy/issues/785

Nothing seems to make it work.

**Comment by chouseknecht** [comment] 2018-07-09 19:32
Well, it actually seems to work with `1.9.4`.

```
$ ansible --version
ansible 1.9.4
  configured module search path = None

$ ansible-galaxy install geerlingguy.ntp,1.3.0
- downloading role 'ntp', owned by geerlingguy
- downloading role from https://github.com/geerlingguy/ansible-role-ntp/archive/1.3.0.tar.gz
- extracting geerlingguy.ntp to /Users/chouseknecht/roles/geerlingguy.ntp
- geerlingguy.ntp was installed successfully
```

**Comment by chouseknecht** [comment] 2018-07-09 19:46
It feels like this is related to the SNI issue, which were working on.

**Comment by chouseknecht** [comment] 2018-07-12 13:03
Closing as a duplicate of #795. We have a workaround for system running Python < 2.7.9 (see #795), and we will add it to our docs.

**Closed by chouseknecht** 2018-07-12 13:03 UTC

**Comment by marcossegovia** [comment] 2018-07-12 13:16
ok @chouseknecht, thanks !
