### ISSUE TITLE
Community namespace vs Community authors

### ISSUE THREAD

**Issue by gundalow** [ansible/galaxy#2149] opened 2019-12-13 13:56 UTC
## Feature Request

`community` will the used as the namespace for most of the content that lives in github.com/ansible-collections/, as requested in https://github.com/ansible/galaxy/issues/2115

However `community` has some special meanings in Galaxy, such as:
* https://galaxy.ansible.com/community

Which need to be moved elsewhere.

**Comment by chouseknecht** [comment] 2019-12-13 13:58
Duplicate of #2145

**Closed by chouseknecht** 2019-12-13 13:58 UTC
Labels: priority/high, type/enhancement
