### ISSUE TITLE
version dropdown lists newest version first, but then in chronological order

### ISSUE THREAD

**Issue by evgeni** [ansible/galaxy#2415] opened 2020-06-22 19:47 UTC
from https://galaxy.ansible.com/theforeman/foreman

![Screenshot from 2020-06-22 14-17-58](https://user-images.githubusercontent.com/94284/85328879-d1d84e80-b4d1-11ea-95fe-b3ebfeda9300.png)

I would have expected to see all versions in reverse chronological order, i.e. 1.0.0, 0.8.1, 0.8.0, 0.7.0 etc as that's IMHO the order of importance someone might be searching for them

**Comment by chouseknecht** [comment] 2020-06-22 21:08
Duplicate of https://github.com/ansible/galaxy/issues/2413

**Closed by chouseknecht** 2020-06-22 21:08 UTC
