### ISSUE TITLE
IMPORTER101: Invalid platform: "Fedora-33", skipping.

### ISSUE THREAD

**Issue by dallinb** [ansible/galaxy#2533] opened 2020-10-30 19:03 UTC
##### SUMMARY
Getting a drop in Metadata score for my role with the following message:

`IMPORTER101: Invalid platform: "Fedora-33", skipping.`

##### STEPS TO REPRODUCE
The platforms section of meta/main.yml looks like this:

```YAML
  platforms:
    - name: EL
      versions:
        - 7
        - 8
    - name: Ubuntu
      versions:
        - bionic
        - focal
        - xenial
    - name: Debian
      versions:
        - buster
        - stretch
    - name: Fedora
      versions:
        - 27
        - 28
        - 29
        - 30
        - 31
        - 32
        - 33
```

##### EXPECTED RESULTS
Fedora 33 final release was 2020-10-27 (see https://fedorapeople.org/groups/schedule/f-33/f-33-key-tasks.html).

##### ACTUAL RESULTS
The message:

`IMPORTER101: Invalid platform: "Fedora-33", skipping.`

is currently visible at https://galaxy.ansible.com/locp/cassandra

**Comment by dallinb** [comment] 2020-12-16 08:20
I must have copied and pasted the description of this issue from my previous issue for Fedora-30, this is actually for Fedora-33.  Apologies for any confusion that may have caused (I do mention Fedora-33 in the expected results).  I also attempted another import today and I still get the same error.  Usually these issues were fixed within hours/days of my reporting them.

Related Issues:
- #1926
- #2105

**Comment by gizero** [comment] 2021-01-11 13:58
Hi! Is there a way we can help with this? It'd be nice to have Fedora 33 among supported platforms. Or did I miss a reason to skip the release?

**Comment by dallinb** [comment] 2021-01-13 11:49
FYI Fedora-32 was fixed in #2356 .  As @gizero says, is there a way we could raise a PR for these issues?  Anything to help expedite the changes basically?  Especially with Fedora having approximately two releases a year.

**Comment by dallinb** [comment] 2021-01-27 13:53
For future reference I'll use this script (https://github.com/dmsimard/ansible-sandbox/tree/master/get-galaxy-platforms) to find out what platforms are supported and not update the metadata until the new platform becomes present.

Could we have an update or ETA on when Fedora 33 will be added to the supported platforms?  It has after all been available since late October.  That was 13 weeks ago and Fedora 34 is due to be released on 20th April (https://fedorapeople.org/groups/schedule/f-34/f-34-key-tasks.html) which is less than 12 weeks from now.

**Comment by dallinb** [comment] 2021-03-24 11:46
Fedora 34 is now in beta release (see https://fedorapeople.org/groups/schedule/f-34/f-34-key-tasks.html) but the latest Fedora supported by Ansible Galaxy is 32 (due for retirement in just under eight weeks from now).

**Comment by bonddim** [comment] 2021-04-29 07:58
Fedora 34 is released and can be added to supported platforms also.

**Comment by coglinev3** [comment] 2021-06-01 06:55
I have the same problem. Please add Fedora 33 and Fedora 34 to supported plattforms.

**Comment by me-vlad** [comment] 2021-06-02 20:26
not exactly fedora related but Ubuntu hirsute (21.04) also missing in a supported platforms list

**Comment by dallinb** [comment] 2021-06-16 13:53
> not exactly fedora related but Ubuntu hirsute (21.04) also missing in a supported platforms list

@me-vlad possibly best to raise a separate ticket for that.  Would be interesting to see if that gets resolved.  This ticket doesn't seem to be going anywhere fast.

**Comment by gotmax23** [comment] 2021-07-30 17:11
@chouseknecht, can you please consider adding Fedora 33, Fedora 34, and Fedora 35 (current Rawhide) to the platforms list?

Thanks,
Maxwell

**Comment by gotmax23** [comment] 2021-09-06 17:45
Is there something preventing the developers from fixing this issue? This seems like a simple change (at least to me), but this issue has been open for almost a year.

Thanks,
Maxwell

**Comment by gotmax23** [comment] 2021-09-06 18:34
Is there something preventing the developers from fixing this issue? This seems like a relatively simple change (at least to me), but this issue has been open for almost a year.

In addition to Fedora 33, there are several other missing platforms. Here is the full list:
1. Fedora 33 (`33` would be the platform version.)
2. Fedora 34 (`34` would be the platform version.)
3. Fedora 35 (`35` would be the platform version; Fedora 35 will be released next month.)
4. Fedora 36 (`36` would be the platform version; Fedora 36 is the current Rawhide.)
5. CentOS Stream 8 and 9 (I think we would need to add a new platform, because I don't think it makes sense to put CentOS Stream under `EL`.)
5. Opensuse Leap 15.3 (`opensuse` would be the platform name and `15.3` would be the platform version.)
6. Opensuse Tumbleweed (I'm not sure if this needs to be a seperate platform or if we should add a `tumbleweed` version to the existing `opensuse` platform.)
7. Ubuntu Hirsute (`hirsute` would be the platform version.)
8. Ubuntu Impish (`impish` would be the codename; Ubuntu 21.10 codenamed Impish will be released next month.)
8. Debian Bookworm (`bookworm` would be be the platform version; Debian 12 codnamed Bookworm is the current Debian testing.)

Thanks,
Maxwell

**Comment by chouseknecht** [comment] 2021-09-23 14:28
Added the following:
- Fedora 33, 34, 35, and 36
- Ubuntu hirsute and impish
- Debian bookwork

**Comment by dmsimard** [comment] 2021-09-23 17:20
Thanks for adding new platforms @chouseknecht \o/

I confirmed that it works via a home made script: https://github.com/dmsimard/ansible-sandbox/commit/363024e19300281123252c2273828f38a628c70b

Someone asked about Rocky Linux a few weeks ago on IRC but I wasn't aware of this issue.
Could we have it added as well ?

**Comment by gotmax23** [comment] 2021-09-23 19:13
Hi,

@dmsimard said:

>  Thanks for adding new platforms @chouseknecht \o/

Thanks again, @chouseknecht! Where do you actually add these platforms? I don't see any new commits to this repository. It would be nice if I could just submit a PR to add missing platform versions in the future.

> Someone asked about Rocky Linux a few weeks ago on IRC but I wasn't aware of this issue.
> Could we have it added as well ?

My understanding is that all RHEL-clones (CentOS, Rocky Linux, Almalinux, Oracle Linux, etc.) are included in the `EL` (Enterprise Linux) platform. I'm not sure about CentOS Stream. I would appreciate input from the developers; users seem to be confused about what `EL` actually is.


@gotmax23 said:

> 6. Opensuse Tumbleweed (I'm not sure if this needs to be a seperate platform or if we should add a `tumbleweed` version to the existing `opensuse` platform.)

What are your thoughts about Tumbleweed?

Thanks,
Maxwell

**Comment by coglinev3** [comment] 2023-02-23 11:42
Please add Fedora 37 to supported releases. The release ist out since 2022-11-15.

**Comment by alisonlhart** [comment] 2023-04-18 18:39
Fedora 37 and 38 added. Closing issue since it is stale. 

Note: Platforms are added by Galaxy admins on the Galaxy backend, not through the codebase, so PR submissions cannot be used for adding platforms.

**Closed by alisonlhart** 2023-04-18 18:39 UTC
