### ISSUE TITLE
ansible-galaxy init role broken for templates with ".git" folder

### ISSUE THREAD

**Issue by eryx12o45** [ansible/galaxy#2507] opened 2020-09-24 11:36 UTC
##### SUMMARY
We used to create roles from a skeleton folder by using the following command:
``
ansible-galaxy init --verbose --role-skeleton=/skeleton-folder role_testrole
``
Since Ansible Galaxy 2.10 this breaks with the following error message (or similar, different file in .git folder):
``
ERROR! Unexpected Exception, this is probably a bug: [Errno 2] No such file or directory: '../role_testrole/role_testrole/.git/ORIG_HEAD'
``
The command copies everything except the .git folder in the skeleton.

##### STACKTRACE
``
Traceback (most recent call last):
  File "/usr/local/bin/ansible-galaxy", line 123, in <module>
    exit_code = cli.run()
  File "/usr/local/lib/python3.8/site-packages/ansible/cli/galaxy.py", line 490, in run
    context.CLIARGS['func']()
  File "/usr/local/lib/python3.8/site-packages/ansible/cli/galaxy.py", line 909, in execute_init
    shutil.copyfile(os.path.join(root, f), os.path.join(obj_path, f_rel_path))
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/shutil.py", line 261, in copyfile
``

##### STEPS TO REPRODUCE
See above

##### EXPECTED RESULTS
A role is initialized based on the template provided without a problem.

##### ACTUAL RESULTS
The role is initialized, except when Ansible Galaxy tries to copy the .git folder, this crashes.

**Comment by sivel** [comment] 2020-10-28 21:06
Duplicate of https://github.com/ansible/ansible/issues/71977

**Closed by sivel** 2020-10-28 21:06 UTC
