### ISSUE TITLE
Missing versions when not using semver

### ISSUE THREAD

**Issue by ryanpineo** [ansible/galaxy#782] opened 2018-07-01 17:36 UTC
##### SUMMARY
For the project https://galaxy.ansible.com/jdauphant/nginx some of the github relases use semver (e.g. v2.9.1) and some do not (e.g. v2.9).  In galaxy only the versions that use semver are appearing in the list.

##### STEPS TO REPRODUCE
View https://galaxy.ansible.com/jdauphant/nginx and observe that some versions are missing that appear in https://github.com/jdauphant/ansible-role-nginx/releases

##### EXPECTED RESULTS
All versions in the github release should be present in galaxy.

##### ACTUAL RESULTS
Only versions that have 3 parts to the version number are appearing.

**Comment by chouseknecht** [comment] 2018-07-01 21:12
That's by design. We're trying to enforce a standardized version format, and we picked Semver.

**Comment by chouseknecht** [comment] 2018-07-01 21:13
Marking this as 'wontfix', because I don't think we want to revert the implementation of Semver.

**Comment by lobsterdore** [comment] 2018-07-02 11:09
We've been hit by this, I think this is a pretty change that might break things for a lot of roles.

**Comment by lobsterdore** [comment] 2018-07-02 11:18
I think some kind or pre-warning via a deprecation notice would have been handy.

**Comment by wojtek-oledzki** [comment] 2018-07-02 11:21
Is support for "v1.2.*" in the pipeline?

Alliteratively what is your suggestion @chouseknecht to point to the latest version of the role?

**Comment by ryanpineo** [comment] 2018-07-02 21:10
Isn't it a bit heavy handed to start enforcing a versioning format, especially when it will break a lot of current projects?

**Comment by chouseknecht** [comment] 2018-07-06 10:41
The ansible-galaxy client has not changed, so any git tag or arbitrary reference can be passed as a version. From that perspective, I believe exiting things will still work. 

The move to enforcing Semantic Version format is so that the client will soon be able to update installed content. Hard to do that though, if it can’t reliably determine and compare versions.

Apologies for the abruptness of the change. We’re trying to move quickly to improve the ecosystem of content, and stem the tide of non-compliant content.

**Comment by peschmae** [comment] 2018-09-25 13:49
While I applaud the intention to aim for a standardization of versioning to allow upgrading of roles without force installing all roles, ejecting versions from galaxy that previously could be installed directly from galaxy, is quite disruptive.

We are either left with the option to change the requirements to point to a github repository and use the no longer supported versioning scheme, or we need to update to a newer role version that conforms to semver just to be able to install it from galaxy.

I hope for future changes that break basic stuff as version listing/detection to be announced earlier, or introduced using a major version bump as intended in semver.

**Closed** 2018-11-15 15:33 UTC
Labels: status/wontfix

**Comment by dougszumski** [comment] 2018-12-05 17:55
We were also hit by this issue. When adding a new semver compliant tag, old, non-compliant tags are no longer available from Galaxy. This breaks a whole load of stuff for us, particular stable branches where we don't necessarily want to upgrade the role version.
