### ISSUE TITLE
Update installer to work with release/3.0

### ISSUE THREAD

**Issue by greenscar** [ansible/galaxy#675] opened 2018-06-17 02:14 UTC
##### SUMMARY
README.md link to "inventory file" broken / file missing

##### STEPS TO REPRODUCE
goto https://github.com/ansible/galaxy/blob/release/3.0/INSTALL.md#pre-deployment-steps
click either of the [inventory](https://github.com/ansible/galaxy/blob/release/3.0/installer/inventory) links.

looking @ the develop branch, there is the *installer* dir... which is missing in 3.0 branch.
##### EXPECTED RESULTS
it works? :)

##### ACTUAL RESULTS
404

**Comment by chouseknecht** [comment] 2018-06-20 19:05
It's on the `develop` branch. Soon we'll merge the two branches and fix the installer. Apologies for the inconvenience.

**Comment by cutwater** [comment] 2018-07-13 09:45
Duplicate of #487

**Closed by cutwater** 2018-07-13 09:45 UTC
Labels: priority/low, status/duplicate, type/bug
