### ISSUE TITLE
Ansible Galaxy can't find available version of role

### ISSUE THREAD

**Issue by isuftin** [ansible/galaxy#3243] opened 2023-09-08 16:23 UTC
##### SUMMARY
Trying to install the role robertdebok.bootstrap version 6.2.0 which Ansible Galaxy shows as available.

https://galaxy.ansible.com/robertdebock/bootstrap

Using ansible-galaxy, unable to install the role. Ansible Galaxy suggests version is not available.

##### STEPS TO REPRODUCE

ansible-galaxy role install --force  robertdebock.bootstrap,6.2.0

##### EXPECTED RESULTS

Role installed at latest version, 6.2.0

##### ACTUAL RESULTS
```sh
ansible-galaxy role install --force  robertdebock.bootstrap,6.2.0
Starting galaxy role install process
- downloading role 'bootstrap', owned by robertdebock
[WARNING]: - robertdebock.bootstrap was NOT installed successfully: - the specified version (6.2.0) of robertdebock.bootstrap was not found in the list of available versions ([{'id': 71490, 'url': '', 'related': {}, 'summary_fields': {},
'created': '2018-07-25T05:57:57.514313Z', 'modified': '2018-08-08T05:41:47.378431Z', 'name': '1.0.0', 'version': '1.0.0', 'commit_date': '2018-08-05T02:13:05-04:00', 'commit_sha': '57a7e5fea87235e6ec51188cb9014abdd2b1db73', 'download_url':
'https://github.com/robertdebock/ansible-role-bootstrap/archive/1.0.0.tar.gz', 'active': None}, {'id': 72323, 'url': '', 'related': {}, 'summary_fields': {}, 'created': '2018-08-10T08:18:05.536947Z', 'modified': '2018-08-10T08:18:05.536977Z',
'name': '2.0.0', 'version': '2.0.0', 'commit_date': '2018-08-10T01:28:10-04:00', 'commit_sha': 'c99563c85bb796a2e9e7953dd6883621b5954b01', 'download_url': 'https://github.com/robertdebock/ansible-role-bootstrap/archive/2.0.0.tar.gz', 'active':
None}, {'id': 72423, 'url': '', 'related': {}, 'summary_fields': {}, 'created': '2018-08-13T15:21:49.028180Z', 'modified': '2018-08-13T15:21:49.028222Z', 'name': '2.1.0', 'version': '2.1.0', 'commit_date': '2018-08-13T10:47:39-04:00',

...

'2021-09-06T09:08:10.538903Z', 'modified': '2021-09-06T09:08:10.538932Z', 'name': '5.2.5', 'version': '5.2.5', 'commit_date': '2021-08-30T12:57:39-04:00', 'commit_sha': '54f5110ae7f793a3e66307b07c3704c0c8d1321e', 'download_url':
'https://github.com/robertdebock/ansible-role-bootstrap/archive/5.2.5.tar.gz', 'active': None}, {'id': 80905, 'url': '', 'related': {}, 'summary_fields': {}, 'created': '2018-11-24T15:16:08.600157Z', 'modified': '2018-11-24T15:16:08.600173Z',
'name': '2.6.1', 'version': '2.6.1', 'commit_date': '2018-11-22T00:18:55-05:00', 'commit_sha': '9c1ab0faaec2adec513b90f1e5b24872d6a6974e', 'download_url': 'https://github.com/robertdebock/ansible-role-bootstrap/archive/2.6.1.tar.gz', 'active':
None}]).
ERROR! - you can use --ignore-errors to skip failed roles and finish processing the list.
```

When not specifying a version, it grabs 6.1.9 which seems to be two versions old.

```sh
ansible-galaxy role install --force robertdebock.bootstrap
Starting galaxy role install process
- changing role robertdebock.bootstrap from 6.1.9 to unspecified
- downloading role 'bootstrap', owned by robertdebock
- downloading role from https://github.com/robertdebock/ansible-role-bootstrap/archive/6.1.9.tar.gz
- extracting robertdebock.bootstrap to /Users/isuftin/.ansible/roles/robertdebock.bootstrap
- robertdebock.bootstrap (6.1.9) was installed successfully
```

**Comment by s-hertel** [comment] 2023-09-08 18:19
This is a duplicate of https://github.com/ansible/galaxy/issues/2912. The version only shows up if the page size is large enough (https://galaxy.ansible.com/api/v1/roles/21642/versions/?page=1&page_size=200).

As a workaround you can install from the Github archive directly `ansible-galaxy role install https://github.com/robertdebock/ansible-role-bootstrap/archive/6.2.0.tar.gz`.

**Comment by isuftin** [comment] 2023-09-08 18:58
@s-hertel Nice find on the dupe. I'll close this issue.

**Closed as completed** 2023-09-08 18:59 UTC
