### ISSUE TITLE
Issue with latest version geerlingguy/ansible-role-php

### ISSUE THREAD

**Issue by mark-jones-entanet** [ansible/galaxy#2089] opened 2019-11-04 07:02 UTC
##### SUMMARY
When trying to get the latest version (3.7.0) of geerlingguy/ansible-role-php from ansible galaxy  using packer the following error is thrown:

```
==> amazon-ebs: [WARNING]: - geerlingguy.php was NOT installed successfully: - the specified
==> amazon-ebs: version (3.7.0) of geerlingguy.php was not found in the list of available
```

##### STEPS TO REPRODUCE
main.yml

`hosts: localhost
  become: true
  vars:
    ansible_python_interpreter: /usr/bin/python3
  roles:
    - geerlingguy.php`

requirements.yml
`- src: geerlingguy.php
  version: 3.7.0`

##### EXPECTED RESULTS
geerlingguy.php is installed.

##### ACTUAL RESULTS
The following error is thrown

```
==> amazon-ebs: [WARNING]: - geerlingguy.php was NOT installed successfully: - the specified
==> amazon-ebs: version (3.7.0) of geerlingguy.php was not found in the list of available
```

Can anyone give me guidance?

**Comment by chouseknecht** [comment] 2019-11-06 17:00
`3.7.0` is failing to import. Not clear why. Will check into it.

**Comment by chouseknecht** [comment] 2019-11-06 17:36
Also, you can see it listed here: https://galaxy.ansible.com/api/v1/roles/432/versions/?page_size=1000

**Comment by chouseknecht** [comment] 2019-11-06 17:45
Seems like the API is doing the right thing and there's a bug in the `ansible-galaxy` client.

**Comment by jborean93** [comment] 2019-11-06 18:58
Duplicate of https://github.com/ansible/ansible/issues/64355 and fixed with https://github.com/ansible/ansible/pull/64373. Will be present in the next 2.9.1 release.

**Closed by jborean93** 2019-11-06 18:58 UTC
