### ISSUE TITLE
Sometimes request to galaxy fail

### ISSUE THREAD

**Issue by robertdebock** [ansible/galaxy#1094] opened 2018-08-24 07:21 UTC
##### SUMMARY
Since today (24th of August 2018) downloads from Galaxy start to fail every now and then.

##### STEPS TO REPRODUCE
```
ansible-galaxy install robertdebock.epel
```

##### EXPECTED RESULTS
Great success!

##### ACTUAL RESULTS
```
 [WARNING]: - robertdebock.epel was NOT installed successfully: Failed to get data from the API server (https://galaxy.ansible.com/api/): ('The read operation timed out',)
```

**Comment by ewypych** [comment] 2018-08-24 08:27
Confirm. The other issue is that from my experience such problems exist EVERY WEEK. Ansible Galaxy is not as stable as should be.

**Comment by Ilhicas** [comment] 2018-08-24 09:07
Confirm intermittent galaxy responses on API from Portugal.
Is there any sort of status page ?
CentOS also having failures such as baseUrl not being found for repo: base/7/x86_64

Redhat issues?

**Comment by robertdebock** [comment] 2018-08-24 10:06
I see more failures than a couple of hours ago, I guess @chouseknecht @cutwater @gregdek and @alikins are waking up by now.

For me other downloaded resources (RPM's and so on) do work as expected, it's only Galaxy that's slow or failing.

**Comment by cutwater** [comment] 2018-08-24 10:42
Thank you for reporting that issue. I confirm that we had an issue on our infrastructure. After latest update cluster didn't scale up properly. This is fixed now.

I created an issue #1095 to for tracking root cause of this issue.

**Closed by cutwater** 2018-08-24 10:42 UTC
