### ISSUE TITLE
Check and improve UI performance

### ISSUE THREAD

**Issue by cutwater** [ansible/galaxy#582] opened 2018-05-25 18:04 UTC
##### SUMMARY
According to users feedback our UI on Galaxy QA site is slow and browser seems to intensively load CPU.

We should profile UI performance and resource utilization and improve it if possible.

**Comment by drybjed** [comment] 2018-05-25 18:11
I'm seeing slowdown on Galaxy pages that display lots of imported repositories/content (currently ~134 things imported). This happens on Debian Jessie with Chromium 57, on Intel i7 CPU with 8 GB of RAM. Whenever I click anything on the page, the tab becomes unresponsive for about 30s-1m.

**Comment by chouseknecht** [comment] 2018-05-30 13:29
Had the same experience on My Content page when there's a large number of repositories. Reworked the Action menus to use components in PR #603 , which seemed to help. Will test more, after that code gets merged and deployed to QA.

**Comment by chouseknecht** [comment] 2018-06-03 11:37
Still work to do on My Content, regarding polling.

**Comment by chouseknecht** [comment] 2018-07-04 16:05
Changing this to enhancement, because I'm not sure we want to immediately back port it to v3.0

**Comment by newswangerd** [comment] 2018-07-06 14:38
There are noticeable slowdowns in UI performance on the My Content page for authors that have lots of imported repos. The issue seems to be caused by the import and delete buttons in the in the repository list

![screen shot 2018-07-06 at 10 32 46 am](https://user-images.githubusercontent.com/6063371/42384455-03552f6e-8108-11e8-9da9-70cb235ee7de.png)

The buttons are implemented as a separate component in angular and as such change detection has to be run on all of them whenever something happens on the page. Disabling change detection doubles the UI responsiveness, but something about rendering all the dropdown menus with the delete button is still causing significant lag whenever any UI actions are triggered. The UI here really needs to be rewritten to include pagination and searching so that we don't have to render so many UI elements.

**Comment by chouseknecht** [comment] 2018-07-06 15:06
Agree that pagination and searching is in order.

The buttons/menus are in components in order to make them dynamic.

**Closed** 2018-08-13 13:34 UTC
Labels: area/frontend, priority/high, status/fix-committed, type/enhancement
