### ISSUE TITLE
Imports fail: "duplicate key value violates unique constraint"

### ISSUE THREAD

**Issue by robertdebock** [ansible/galaxy#793] opened 2018-07-02 12:01 UTC
##### SUMMARY
Since the new version of Ansible Galaxy (thanks for that by the way), some imports fail with this error:
```
Task "258482" failed: duplicate key value violates unique constraint "main_content_namespace_id_repository__d7de6a83_uniq" DETAIL: Key (namespace_id, repository_id, name, content_type_id)=(4003, 53988, buildtools, 11) already exists.
```

##### STEPS TO REPRODUCE
1. Login to Ansible Galaxy.
2. Search some role, i.e. [this role](https://galaxy.ansible.com/my-imports?namespace=robertdebock&selected=258182)
3. Hit the `restart import` button.
4. Read the error in the console.

##### EXPECTED RESULTS
Another successful import. ;-)

##### ACTUAL RESULTS
```

INFO Starting import: task_id=258482, repository=robertdebock/ansible-role-buildtools
WARNING [role] 'Alpine' is not a valid tag. Tags must container lowercase letters and digits only. Skipping.
WARNING [role] 'CentOS' is not a valid tag. Tags must container lowercase letters and digits only. Skipping.
WARNING [role] 'Fedora' is not a valid tag. Tags must container lowercase letters and digits only. Skipping.
WARNING [role] 'Debian' is not a valid tag. Tags must container lowercase letters and digits only. Skipping.
WARNING [role] 'Ubuntu' is not a valid tag. Tags must container lowercase letters and digits only. Skipping.
WARNING [role] 'RHEL' is not a valid tag. Tags must container lowercase letters and digits only. Skipping.
INFO [role] Linting...
INFO [role] Linting OK.
Task "258482" failed: duplicate key value violates unique constraint "main_content_namespace_id_repository__d7de6a83_uniq" DETAIL: Key (namespace_id, repository_id, name, content_type_id)=(4003, 53988, buildtools, 11) already exists.
```

**Comment by chouseknecht** [comment] 2018-07-02 13:15
@robertdebock 

Thanks for reporting this. It's actually a duplicate of #776. We're working on it, and should have a fix in production by tomorrow morning.

**Closed by chouseknecht** 2018-07-02 13:15 UTC
