### ISSUE TITLE
Task "XXXXXX" failed: value too long for type character varying(256) 

### ISSUE THREAD

**Issue by githubixx** [ansible/galaxy#1415] opened 2018-12-12 19:34 UTC
##### SUMMARY
Since a few days I can't import some of my repositories anymore. The error is:

```
Updating repository versions...
Task "336836" failed: value too long for type character varying(256) 
```
It's absolutely unclear to me what this error is all about.

##### STEPS TO REPRODUCE
I simply try to import e.g. https://galaxy.ansible.com/githubixx/kubectl . That's not the only one. Some others fail too with the same error.

##### EXPECTED RESULTS
Import should succeed as it did for month without issues. At least the error message should give some kind of information what is expected and not just fail without any information.

##### ACTUAL RESULTS
```
Updating repository versions...
Task "336836" failed: value too long for type character varying(256) 
```
Any hint welcome ;-) Thanks!

**Comment by cutwater** [comment] 2018-12-13 13:33
Hi @githubixx,

Thank you for reporting this issue. I can confirm the issue, it's related with our internal database model restrictions that should be fixed. Unfortunately I don't think there is any workaround possible until we release a fix.

**Comment by cutwater** [comment] 2018-12-13 14:10
Update: After analyzing the particular failure I can suggest one workaround to sucessfully import a role patch is released. The import process fails because of warning string length is too long:

 > Galaxy will only import git tags that match the semantic version format, skipping these tag(s): r1.0.0_v1.8.0, r3.0.1_v1.10.4, r3.0.0_v1.10.4, r2.0.0_v1.9.1, r2.0.2_v1.9.1, r1.0.2_v1.8.0, r6.0.0_v1.13.0, r6.0.1_v1.13.0, r5.0.1_v1.12.1, r3.0.2_v1.10.8, r2.0.1_v1.9.1, r5.0.0_v1.12.0

Therefore you could've fix github tags or reduce their number.

I'm currently working on the patch and it will be released ASAP (tonight \ tomorrow morning).

**Comment by githubixx** [comment] 2018-12-13 14:30
Thanks for the update! I already suspected that it has something to do with the tags. But I don't want to change existing tags as user may rely on it. But I guess I'll change the tag format in the future. On the other hand I don't understand why Galaxy enforces semantic version format. While it makes sense for quite few projects maybe not all want to use it. I guess there're quite a few Ansible roles out there that use other version/tag formats which works quite well for them but now forced to switch.

**Closed** 2018-12-14 15:51 UTC
Labels: area/backend, priority/critical, type/bug
