### ISSUE TITLE
'Error when finding available api versions' message

### ISSUE THREAD

**Issue by opdavies** [ansible/galaxy#2242] opened 2020-02-13 15:05 UTC
##### SUMMARY
When trying to install new roles to my project, I'm now seeing this message:

```
[WARNING]: - opdavies.drupal_settings_files was NOT installed successfully: Error when finding available api versions from
default (https://galaxy.ansible.com) (HTTP Code: 404, Message: Not Found)
```

I wondered if I was due to it being a new role, but it's also happening for established roles like `geerlingguy.certbot`.

##### STEPS TO REPRODUCE
Run `ansible-galaxy install opdavies.drupal_settings_files`.

The same error happens if I try and run it from a `requirements.yml` file.

##### EXPECTED RESULTS
The role would be installed.

##### ACTUAL RESULTS
The error message is displayed and the role is not installed. I'm using Ansible version 2.9.4.

**Comment by opdavies** [comment] 2020-02-13 17:05
The same command works though on a different laptop, though that is running Ansible 2.9.3.

**Comment by chouseknecht** [comment] 2020-02-13 19:07
Seems like an `ansible-galaxy` bug that should be filed in the [ansible](https://github.com/ansible/ansible) project.

**Comment by opdavies** [comment] 2020-02-18 23:27
@chouseknecht Do I need to create a new issue, or can you transfer it?

**Comment by opdavies** [comment] 2020-02-18 23:29
I've managed to fix it for now by downgrading to Ansible 2.8.7 using Homebrew as I'm running macOS:

```
brew tap homebrew/cask-versions

brew install ansible@2.8

brew unlink ansible && brew link ansible@2.8 --force
```

After which, `ansible --version` is 2.8.7.

Running the original command, e.g. `ansible-galaxy install -r tools/ansible/requirements.yml` now works as expected.

**Comment by chouseknecht** [comment] 2020-02-19 13:17
@opdavies 

I believe the issue you're running into is specific to your environment. If `ansible-galaxy` can't reach or connect to `https://galaxy.ansible.com/api`, it catches the error and tries `https://galaxy.ansible.com/api/api`, which of course fails and returns the error you're seeing.

My environment was returning the same until I killed Kaspersky. For some reason that was interfering with `https` requests. Once I killed the `kav` process, `ansible-galaxy` started working fine.

Here's running the latest code from the `devel` branch of ansible:

```
ansible-galaxy install -vvvv opdavies.drupal_settings_files
ansible-galaxy 2.10.0.dev0
  config file = /Users/chouseknecht/ansible.cfg
  configured module search path = [u'/Users/chouseknecht/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/chouseknecht/projects/ansible/lib/ansible
  executable location = /Users/chouseknecht/.pyenv/versions/venv27/bin/ansible-galaxy
  python version = 2.7.14 (default, Nov 14 2017, 23:24:24) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.38)]
Using /Users/chouseknecht/ansible.cfg as config file
Processing role opdavies.drupal_settings_files
Initial connection to galaxy_server: https://galaxy.ansible.com
Opened /Users/chouseknecht/.ansible/galaxy_token
Calling Galaxy at https://galaxy.ansible.com/api/
Found API version 'v1, v2' with Galaxy server default (https://galaxy.ansible.com/api/)
- downloading role 'drupal_settings_files', owned by opdavies
Opened /Users/chouseknecht/.ansible/galaxy_token
Calling Galaxy at https://galaxy.ansible.com/api/v1/roles/?owner__username=opdavies&name=drupal_settings_files
Opened /Users/chouseknecht/.ansible/galaxy_token
Calling Galaxy at https://galaxy.ansible.com/api/v1/roles/46512/versions/?page_size=50
- downloading role from https://github.com/opdavies/ansible-role-drupal-settings/archive/master.tar.gz
- extracting opdavies.drupal_settings_files to /Users/chouseknecht/roles/opdavies.drupal_settings_files
- opdavies.drupal_settings_files (master) was installed successfully
```

**Comment by chouseknecht** [comment] 2020-02-19 13:29
@opdavies 

Here it is working with `2.9.4`:

ansible-galaxy install -vvvv opdavies.drupal_settings_files
ansible-galaxy 2.9.4
  config file = /Users/chouseknecht/ansible.cfg
  configured module search path = [u'/Users/chouseknecht/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/chouseknecht/projects/ansible/lib/ansible
  executable location = /Users/chouseknecht/.pyenv/versions/venv27/bin/ansible-galaxy
  python version = 2.7.14 (default, Nov 14 2017, 23:24:24) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.38)]
Using /Users/chouseknecht/ansible.cfg as config file
Processing role opdavies.drupal_settings_files
Initial connection to galaxy_server: https://galaxy.ansible.com
Opened /Users/chouseknecht/.ansible/galaxy_token
Calling Galaxy at https://galaxy.ansible.com/api/
Found API version 'v1, v2' with Galaxy server default (https://galaxy.ansible.com/api/)
- downloading role 'drupal_settings_files', owned by opdavies
Opened /Users/chouseknecht/.ansible/galaxy_token
Calling Galaxy at https://galaxy.ansible.com/api/v1/roles/?owner__username=opdavies&name=drupal_settings_files
Opened /Users/chouseknecht/.ansible/galaxy_token
Calling Galaxy at https://galaxy.ansible.com/api/v1/roles/46512/versions/?page_size=50
- downloading role from https://github.com/opdavies/ansible-role-drupal-settings/archive/master.tar.gz
- extracting opdavies.drupal_settings_files to /Users/chouseknecht/roles/opdavies.drupal_settings_files
- opdavies.drupal_settings_files (master) was installed successfully

**Comment by chouseknecht** [comment] 2020-02-19 13:32
Closing. This issue is not a bug in ansible. It seems to be something related to the user's environment. Also, issues related to `ansible-galaxy` should be opened in the Ansible project.

**Closed by chouseknecht** 2020-02-19 13:32 UTC
Labels: area/client, priority/low, status/new, type/bug
