### ISSUE TITLE
On My Imports, change Namespace filter to 'iexact' rather than 'icontains'

### ISSUE THREAD

**Issue by lae** [ansible/galaxy#781] opened 2018-07-01 14:32 UTC
##### SUMMARY
Roles from other users who happen to have "lae" in their name are showing up in my imports - I assume this might be happening to others as well.

##### STEPS TO REPRODUCE
Visit My Imports (e.g. https://galaxy.ansible.com/my-imports?namespace=lae)

##### EXPECTED RESULTS
Only roles that I have access to should show up.

##### ACTUAL RESULTS
![](https://up.lae.is/i/1530455180-1bd2c.png)

**Comment by chouseknecht** [comment] 2018-07-01 21:08
That's by design. You can view all imports, even though the page is called 'My Imports'. However, you can only initiate an import for a repository where you're an owner in the Namespace.

As far as the filter is concerned, the query behind this is doing a partial match. In other words, it's searching for a Namespace.name that contains 'lae'. You can narrow it down of course, by adding repository name.

We could remove the partial match, and make it an exact match. Maybe that would be less confusing.

**Comment by chouseknecht** [comment] 2018-07-02 19:31
Closed by #788

**Closed by chouseknecht** 2018-07-02 19:31 UTC
Labels: area/client, priority/low, type/bug
