### ISSUE TITLE
Redirect /intro -> /docs/

### ISSUE THREAD

**Issue by alexandrevicenzi** [ansible/galaxy#830] opened 2018-07-04 15:25 UTC
##### SUMMARY

[https://galaxy.ansible.com/intro](https://galaxy.ansible.com/intro) returns 404.

This page is one of the first results in Google and is also referred in Ansible documentation.

Is this 404 an expected result? Did this page move to somewhere else?

##### STEPS TO REPRODUCE

Visit [https://galaxy.ansible.com/intro](https://galaxy.ansible.com/intro).

**Comment by chouseknecht** [comment] 2018-07-04 15:51
It's removed, but we should add a redirect to http://galaxy.ansible.com/docs/

**Comment by akaRem** [comment] 2018-07-16 11:45
duplicate of https://github.com/ansible/galaxy/issues/822

**Comment by akaRem** [comment] 2018-07-17 10:57
@cutwater Ah, ok. I was mislead by the same titles.

**Closed** 2018-07-20 09:32 UTC
Labels: area/infrastructure, priority/high, status/fix-released, type/bug
