### ISSUE TITLE
importing role fails with "duplicate key value violates unique constraint"

### ISSUE THREAD

**Issue by nusenu** [ansible/galaxy#780] opened 2018-07-01 11:26 UTC
##### SUMMARY

restarting a role import fails (functionality that worked until now)

##### STEPS TO REPRODUCE

click on 'restart import'

##### EXPECTED RESULTS

the role is imported

##### ACTUAL RESULTS
import fails and this error shows:

```
INFO Starting import: task_id=257999, repository=nusenu/ansible-relayor
INFO [role] Linting...
INFO [role] Linting OK.
Task "257999" failed: duplicate key value violates unique constraint "main_content_namespace_id_repository__d7de6a83_uniq" DETAIL: Key (namespace_id, repository_id, name, content_type_id)=(3616, 30810, relayor, 11) already exists.
```

**Comment by chouseknecht** [comment] 2018-07-01 21:02
@nusenu Thanks for reporting this. It's actually a duplicate of #775 and #776, and we're working on it. Closing for now. We plant to have a fix out on Monday or Tuesday at the latest. Thanks for your patience.

**Closed by chouseknecht** 2018-07-01 21:02 UTC
