### ISSUE TITLE
Update Galaxy Username

### ISSUE THREAD

**Issue by kinglouie** [ansible/galaxy#309] opened 2018-01-25 08:51 UTC
I recently changed my GitHub username from KingLoui to kinglouie. I can not find any option on galaxy to reflect the name change from GitHub. I don't know if this has any impact on the role I provide on galaxy.

**Comment by chouseknecht** [comment] 2018-01-28 11:54
Thanks for using Galaxy, and reporting this issue. We appreciate your feedback. 

As noted in #310, changing your GitHub account name, changes the namespace of your roles. Therefore, you will need to go to `My Content`, and toggle the switch to the left of the role. Moving it to an `X` will delete it from Galaxy, and moving it back to a check mark will re-import it, putting it into the new namespace.

I'm going to close this issue, since it is a duplicate of #310. However, if you require any assistance with your account or roles, please comment on #310, and let us know.

**Closed by chouseknecht** 2018-01-28 11:54 UTC
