### ISSUE TITLE
"Ansible-galaxy init" command doesn't deploy .travis.yml in generated scaffolding

### ISSUE THREAD

**Issue by bartekgb** [ansible/galaxy#659] opened 2018-06-12 17:19 UTC
##### SUMMARY
"Ansible-galaxy init" command doesn't deploy .travis.yml in generated scaffolding.

According to doc at [https://docs.ansible.com/ansible/latest/reference_appendices/galaxy.html#create-roles](url) and [https://galaxy.ansible.com/intro#travis](url):

> NOTE: For a full .travis.yml example run ansible-galaxy init. Starting in Ansible 2.0 the generated scaffolding includes a working .travis.yml file and related tests folder.

Either fix the doc or actual command run results.

Ansible version: 2.5.4

##### STEPS TO REPRODUCE
Run "ansible-galaxy init rolename" to create the role scaffolding.

##### EXPECTED RESULTS

```
README.md
.travis.yml
defaults/
    main.yml
files/
handlers/
    main.yml
meta/
    main.yml
templates/
tests/
    inventory
    test.yml
vars/
    main.yml
````

##### ACTUAL RESULTS
````
./README.md
./handlers
./handlers/main.yml
./templates
./defaults
./defaults/main.yml
./vars
./vars/main.yml
./files
./meta
./meta/main.yml
./tests
./tests/test.yml
./tests/inventory
./tasks
./tasks/main.yml

**Comment by chouseknecht** [comment] 2018-06-12 20:18
This used to work. Will investigate.

**Comment by Akasurde** [comment] 2018-06-13 17:11
I am not able to reproduce this -

```
# ansible --version
ansible 2.5.5.dev0 (stable25 456af458fc) last updated 2018/06/13 09:54:34 (GMT +550)
  config file = /Users/akasurde/.ansible.cfg
  configured module search path = ['/Users/akasurde/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Volumes/data/src/ansible/lib/ansible
  executable location = /Volumes/data/src/ansible/bin/ansible
  python version = 3.6.4 (default, Dec 19 2017, 15:24:51) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)]
# ansible-galaxy init sample_role
- sample_role was created successfully
# cd sample_role
# ls
README.md defaults  files     handlers  meta      tasks     templates tests     vars
# ls -la
total 16
drwxr-xr-x   12 akasurde  staff   408 Jun 13 22:38 .
drwxr-xr-x  159 akasurde  staff  5406 Jun 13 22:38 ..
-rw-r--r--    1 akasurde  staff   539 Jun 13 22:38 .travis.yml
-rw-r--r--    1 akasurde  staff  1328 Jun 13 22:38 README.md
drwxr-xr-x    3 akasurde  staff   102 Jun 13 22:38 defaults
drwxr-xr-x    2 akasurde  staff    68 Jun 13 22:38 files
drwxr-xr-x    3 akasurde  staff   102 Jun 13 22:38 handlers
drwxr-xr-x    3 akasurde  staff   102 Jun 13 22:38 meta
drwxr-xr-x    3 akasurde  staff   102 Jun 13 22:38 tasks
drwxr-xr-x    2 akasurde  staff    68 Jun 13 22:38 templates
drwxr-xr-x    4 akasurde  staff   136 Jun 13 22:38 tests
drwxr-xr-x    3 akasurde  staff   102 Jun 13 22:38 vars
```

**Comment by bartekgb** [comment] 2018-06-14 12:05
Ok i managed to find the source of the problem: I installed ansible on Ubuntu Xenial via deb package from ppa:ansible/ansible and this is where problem persists. When i checked out ansible directly from repo and used even the same version the issue was gone.

The ".travis.yml" file in the directory with the role skeleton template in installed deb package is missing:

Ansible checkoud out from sources:
````
:~/ansible/lib/ansible/galaxy# find -type f -name ".travis.yml"
./data/default/.travis.yml
./data/container_enabled/.travis.yml
````
Ansible installed via Ubuntu's package manager:
````
:/usr/lib/python2.7/dist-packages/ansible/galaxy# find -type f -name ".travis.yml"
:/usr/lib/python2.7/dist-packages/ansible/galaxy#
````

Where would be the correct place to report this issue then (i guess not here)?

**Comment by chouseknecht** [comment] 2018-06-28 18:21
Verified that `ansible-galaxy init` from `devel` indeed installs the `.travis.yml` file. Closing.

**Closed by chouseknecht** 2018-06-28 18:21 UTC
Labels: area/client, priority/low, type/bug

**Comment by spagu** [comment] 2019-08-16 00:48
Mid 2019 and still not getting .travis.yml file.
