### ISSUE TITLE
JS lint "recommended" 

### ISSUE THREAD

**Issue by chouseknecht** [ansible/galaxy#860] opened 2018-07-11 10:59 UTC
Add `"extends": "tslint:recommended",` to `tslint.json`, and fix the resulting JS errors. Most of the errors can be addressed by then running `ts lint galaxyui --fix` from within the `galaxyui` folder.

**Comment by akaRem** [comment] 2018-07-11 21:01
I've made some changes but there are some rules to discuss (probably).
Currently these rules are muted:
```
    "align": false,
    "array-type": false,
    "arrow-parens": false,
    "ban-types": false,
    "interface-name": false,
    "jsdoc-format": false,
    "max-classes-per-file": false,
    "no-consecutive-blank-lines": false,
    "object-literal-key-quotes": false,
    "object-literal-shorthand": false,
    "prefer-for-of": false,
    "trailing-comma": false,
```
You can read more about each of them on TSlint site [1]

I also didn't include rule for unused variables.

From my POV stricter linter is better in most of cases. But team may have another view on this.

The questions are:
1) Should I fix unused imports?
2) Which rules to enable?
3) There are some overrides like max-line-length, whitespace and others.. Should I drop them in favour of recommended or not?

If PR is Ok, then after it's merged, I will probably be able to add multiple PRs for different rules which will not conflict with each other and allow easier review and decision making process.

Full list of recommended rules is available in crsp repo [2]

[1] https://palantir.github.io/tslint/rules/
[2] https://github.com/palantir/tslint/blob/master/src/configs/recommended.ts

**Comment by newswangerd** [comment] 2018-07-12 15:34
@akaRem Nice work! I approved #866 and I think it's a pretty good starting point.

To answer your questions:
1. We definitely want to check for unused imports/variables
2. I would enable Align. The rest that you've disabled seem reasonable to me.
3. I would prefer to leave the current overrides as they are.

**Comment by akaRem** [comment] 2018-07-12 16:47
@newswangerd ok, I'll add these checks too.
I think it's better to do it with separate PR because that PR is already big enough.

I will probably propose other PRs with enabled checks plus fixes so team may look and decide which format looks more preferred.

**Comment by akaRem** [comment] 2018-07-16 11:43
Related PRs: https://github.com/ansible/galaxy/pull/866 https://github.com/ansible/galaxy/pull/890 https://github.com/ansible/galaxy/pull/891 https://github.com/ansible/galaxy/pull/892 https://github.com/ansible/galaxy/pull/893

**Comment by newswangerd** [comment] 2018-07-16 16:52
@akaRem #891 needs to be re-based before I can merge it. Also, see my comment on #893.

Thanks for your help!

**Comment by newswangerd** [comment] 2018-07-20 15:48
@akaRem What's the status on checking for unused imports? That's something that we really need to get done.

**Comment by akaRem** [comment] 2018-07-23 09:21
@newswangerd I didn't have much time last week. I'll make it on this one.

**Comment by newswangerd** [comment] 2018-07-23 13:40
@akaRem No worries! I appreciate that you take the time to contribute.

**Comment by akaRem** [comment] 2018-07-23 15:02
@newswangerd 
PR https://github.com/ansible/galaxy/pull/950 

The problem is that there are no rules for "unused imports". Tslint supports only "unused variables" rule, which covers imports but also forces to fix some other cases. I'm React guy, so I'm not sure, which statements could be dropped and which must not be dropped in Angular code.. So I just muted some lines.

They are mostly about the same (router, xxxService and few others), so If you can suggest how to fix them, I'll do it.

But anyways, it'l be great if you review this change and merge it if everything is ok in other cases.

PS: I'm also planning to add patch regarding spaces in import statements, and you may close this issue on that point as completed. (IMHO)

**Comment by newswangerd** [comment] 2018-07-23 16:09
@akaRem I'll make some time to review #950 this afternoon.

Also, please don't make any changes to that require us to remove spacing for formatting our imports.

I think it's important to leave imports formatted like this:

```
import { Action }             from 'patternfly-ng/action/action';
import { ActionConfig }       from 'patternfly-ng/action/action-config';
import { EmptyStateConfig }   from 'patternfly-ng/empty-state/empty-state-config';
import { Filter }             from 'patternfly-ng/filter/filter';
import { FilterConfig }       from 'patternfly-ng/filter/filter-config';
import { FilterEvent }        from 'patternfly-ng/filter/filter-event';
import { FilterField }        from 'patternfly-ng/filter/filter-field';
```

Where the `from` clause is always at roughly the same level of indentation. It's a lot easier to read this way than forcing imports to only have one space such as:
```
import { Action } from 'patternfly-ng/action/action';
import { ActionConfig } from 'patternfly-ng/action/action-config';
import { EmptyStateConfig } from 'patternfly-ng/empty-state/empty-state-config';
import { Filter } from 'patternfly-ng/filter/filter';
import { FilterConfig } from 'patternfly-ng/filter/filter-config';
import { FilterEvent } from 'patternfly-ng/filter/filter-event';
import { FilterField } from 'patternfly-ng/filter/filter-field';

```

**Comment by newswangerd** [comment] 2018-08-02 19:59
@akaRem we're adding formatting with prettier which destroys all of our beautiful readable imports, so ignore that last comment.

#1004

**Closed** 2018-10-12 16:49 UTC
Labels: area/frontend, priority/low, type/bug
